### ISSUE TITLE
ruby 2.5.0dev (2017-11-10 trunk 60739) [x86_64-linux-gnu] breaks ruby-prof

### ISSUE THREAD

**Issue by darix** [ruby-prof/ruby-prof#227]
```
ruby_prof.c: In function ‘prof_event_hook’:
ruby_prof.c:183:9: warning: ‘rb_frame_method_id_and_class’ is deprecated [-Wdeprecated-declarations]
         rb_frame_method_id_and_class(&mid, &klass);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/ruby-2.5.0/ruby/ruby.h:24:0,
                 from /usr/include/ruby-2.5.0/ruby.h:33,
                 from ruby_prof.h:7,
                 from ruby_prof.c:26:
/usr/include/ruby-2.5.0/ruby/backward.h:53:37: note: declared here
 DECLARE_DEPRECATED_INTERNAL_FEATURE(rb_frame_method_id_and_class);
                                     ^
/usr/include/ruby-2.5.0/x86_64-linux-gnu/ruby/config.h:130:52: note: in definition of macro ‘NORETURN’
 #define NORETURN(x) __attribute__ ((__noreturn__)) x
                                                    ^
/usr/include/ruby-2.5.0/ruby/backward.h:39:14: note: in expansion of macro ‘ERRORFUNC’
     NORETURN(ERRORFUNC(("deprecated internal function"), DEPRECATED(void func(void))))
              ^~~~~~~~~
/usr/include/ruby-2.5.0/ruby/backward.h:39:58: note: in expansion of macro ‘DEPRECATED’
     NORETURN(ERRORFUNC(("deprecated internal function"), DEPRECATED(void func(void))))
                                                          ^~~~~~~~~~
/usr/include/ruby-2.5.0/ruby/backward.h:53:1: note: in expansion of macro ‘DECLARE_DEPRECATED_INTERNAL_FEATURE’
 DECLARE_DEPRECATED_INTERNAL_FEATURE(rb_frame_method_id_and_class);
 ^
ruby_prof.c:183:9: error: too many arguments to function ‘rb_frame_method_id_and_class’
         rb_frame_method_id_and_class(&mid, &klass);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/ruby-2.5.0/ruby/ruby.h:24:0,
                 from /usr/include/ruby-2.5.0/ruby.h:33,
                 from ruby_prof.h:7,
                 from ruby_prof.c:26:
/usr/include/ruby-2.5.0/ruby/backward.h:53:37: note: declared here
 DECLARE_DEPRECATED_INTERNAL_FEATURE(rb_frame_method_id_and_class);
                                     ^
/usr/include/ruby-2.5.0/x86_64-linux-gnu/ruby/config.h:130:52: note: in definition of macro ‘NORETURN’
 #define NORETURN(x) __attribute__ ((__noreturn__)) x
                                                    ^
/usr/include/ruby-2.5.0/ruby/backward.h:39:14: note: in expansion of macro ‘ERRORFUNC’
     NORETURN(ERRORFUNC(("deprecated internal function"), DEPRECATED(void func(void))))
              ^~~~~~~~~
/usr/include/ruby-2.5.0/ruby/backward.h:39:58: note: in expansion of macro ‘DEPRECATED’
     NORETURN(ERRORFUNC(("deprecated internal function"), DEPRECATED(void func(void))))
                                                          ^~~~~~~~~~
/usr/include/ruby-2.5.0/ruby/backward.h:53:1: note: in expansion of macro ‘DECLARE_DEPRECATED_INTERNAL_FEATURE’
 DECLARE_DEPRECATED_INTERNAL_FEATURE(rb_frame_method_id_and_class);
 ^
make: *** [Makefile:242: ruby_prof.o] Error 1
ERROR:  Error installing /home/abuild/rpmbuild/SOURCES/ruby-prof-0.16.2.gem:
        ERROR: Failed to build gem native extension.

    Building has failed. See above output for more information on the failure.
make failed, exit code 2
```

**Comment by rdp** [comment]
what failure do you get?

**Comment by kyoshidajp** [comment]
I was able to reproduce a similar error.

And, I'm using rbenv. The following is an error log.

```
% ruby -v
ruby 2.5.0dev (2017-11-16 trunk 60794) [x86_64-darwin16]
% gem install ruby-prof
Building native extensions. This could take a while...
ERROR:  Error installing ruby-prof:
	ERROR: Failed to build gem native extension.

    current directory: /Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/ruby-prof-0.16.2/ext/ruby_prof
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/bin/ruby -r ./siteconf20171116-67807-q1hj19.rb extconf.rb
checking for rb_gc_stat()... yes
checking for rb_gc_count()... yes
checking for rb_os_allocated_objects()... no
checking for rb_gc_allocated_size()... no
checking for rb_gc_collections()... no
checking for rb_gc_time()... no
checking for rb_gc_total_time()... no
checking for rb_gc_total_mallocs()... no
checking for rb_gc_total_malloced_bytes()... no
checking for rb_heap_total_mem()... no
checking for rb_gc_heap_info()... no
creating Makefile

current directory: /Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/ruby-prof-0.16.2/ext/ruby_prof
make "DESTDIR=" clean

current directory: /Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/ruby-prof-0.16.2/ext/ruby_prof
make "DESTDIR="
compiling rp_call_info.c
compiling rp_measure.c
compiling rp_measure_allocations.c
compiling rp_measure_cpu_time.c
compiling rp_measure_gc_runs.c
compiling rp_measure_gc_time.c
compiling rp_measure_memory.c
compiling rp_measure_process_time.c
compiling rp_measure_wall_time.c
compiling rp_method.c
compiling rp_stack.c
compiling rp_thread.c
compiling ruby_prof.c
ruby_prof.c:183:9: warning: 'rb_frame_method_id_and_class' is deprecated [-Wdeprecated-declarations]
        rb_frame_method_id_and_class(&mid, &klass);
        ^
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/backward.h:53:37: note: 'rb_frame_method_id_and_class' has been explicitly marked deprecated here
DECLARE_DEPRECATED_INTERNAL_FEATURE(rb_frame_method_id_and_class);
                                    ^
ruby_prof.c:183:38: error: too many arguments to function call, expected 0, have 2
        rb_frame_method_id_and_class(&mid, &klass);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/backward.h:53:1: note: 'rb_frame_method_id_and_class' declared here
DECLARE_DEPRECATED_INTERNAL_FEATURE(rb_frame_method_id_and_class);
^
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/backward.h:39:5: note: expanded from macro 'DECLARE_DEPRECATED_INTERNAL_FEATURE'
    NORETURN(ERRORFUNC(("deprecated internal function"), DEPRECATED(void func(void))))
    ^
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/x86_64-darwin16/ruby/config.h:123:21: note: expanded from macro 'NORETURN'
#define NORETURN(x) __attribute__ ((__noreturn__)) x
                    ^
ruby_prof.c:406:13: warning: division by zero is undefined [-Wdivision-by-zero]
    switch (rb_scan_args(argc, argv, "02", &mode_or_options, &exclude_threads)) {
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2172:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2345:9: note: expanded from macro 'rb_scan_args0'
                     (rb_scan_args_verify(fmt, varc), vars))
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2230:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2196:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2191:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2187:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ruby_prof.c:406:13: warning: division by zero is undefined [-Wdivision-by-zero]
    switch (rb_scan_args(argc, argv, "02", &mode_or_options, &exclude_threads)) {
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2172:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2345:9: note: expanded from macro 'rb_scan_args0'
                     (rb_scan_args_verify(fmt, varc), vars))
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2230:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2196:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2192:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs+1, varc, vari+1))
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2187:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ruby_prof.c:406:13: warning: division by zero is undefined [-Wdivision-by-zero]
    switch (rb_scan_args(argc, argv, "02", &mode_or_options, &exclude_threads)) {
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2172:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2345:9: note: expanded from macro 'rb_scan_args0'
                     (rb_scan_args_verify(fmt, varc), vars))
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2230:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2197:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs+1, varc, vari+1))
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2191:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2187:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ruby_prof.c:406:13: warning: division by zero is undefined [-Wdivision-by-zero]
    switch (rb_scan_args(argc, argv, "02", &mode_or_options, &exclude_threads)) {
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2172:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2345:9: note: expanded from macro 'rb_scan_args0'
                     (rb_scan_args_verify(fmt, varc), vars))
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2230:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2196:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2191:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2187:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ruby_prof.c:406:13: warning: division by zero is undefined [-Wdivision-by-zero]
    switch (rb_scan_args(argc, argv, "02", &mode_or_options, &exclude_threads)) {
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2172:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2345:9: note: expanded from macro 'rb_scan_args0'
                     (rb_scan_args_verify(fmt, varc), vars))
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2230:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2196:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2191:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2187:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ruby_prof.c:406:13: warning: division by zero is undefined [-Wdivision-by-zero]
    switch (rb_scan_args(argc, argv, "02", &mode_or_options, &exclude_threads)) {
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2172:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2345:9: note: expanded from macro 'rb_scan_args0'
                     (rb_scan_args_verify(fmt, varc), vars))
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2230:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 5 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2196:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2191:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/include/ruby-2.5.0/ruby/ruby.h:2187:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
7 warnings and 1 error generated.
make: *** [ruby_prof.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/ruby-prof-0.16.2 for inspection.
Results logged to /Users/katsuhiko.yoshida/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-16/2.5.0-static/ruby-prof-0.16.2/gem_make.out
```

**Comment by kyoshidajp** [comment]
It seems like because of ruby/ruby@b6946d31fc201f6e6a5e046d58b69fa377bb76af.

Before the commit, I was able to install successfully. However, I'm not sure why the commit is included.

**Comment by darix** [comment]
I posted the error message later. it was just missing in the initial post due to fat fingers.

**Comment by k0kubun** [comment]
This issue was fixed in https://github.com/ruby/ruby/commit/857827e3eed915543ac9d4d2541179ea4ded8eee. But this API will be deprecated from Ruby 2.5 and we should stop its usage.

**Comment by skaes** [comment]
@k0kubun the issue is not fixed because ruby does not export the symbol from the library.

**Comment by skaes** [comment]
See https://bugs.ruby-lang.org/issues/14192

**Comment by skaes** [comment]
Fixed by https://github.com/ruby/ruby/commit/316f58076d29dcff053256992d9ec19fed7e698f

**Comment by rdp** [comment]
Nice work.
